### ISSUE TITLE
Unknown string format. Only for particular dates.

### ISSUE THREAD

**Issue by tomerarnon** [space-physics/msise00#12]
The date `t = datetime(2019, 10, 30, 0, 0)` throws a value error: `*** ValueError: Unknown string format` when calling `msise00.run(time=t, altkm=alt, glat=glat, glon=glon)`

Changing the year, month or day works exactly as expected however. So it's just this particular date that is the problem. Any idea what could be happening here?

**Comment by tomerarnon** [comment]
@dcsozturk I've tried other future dates that work fine. Incrementing by a few months to  `datetime(2019, 12, 30)` makes it work, for example. I'm not sure what is wrong with that precise datetime...

**Comment by dcsozturk** [comment]
I couldn't reproduce the error for t = datetime(2019,10,30,0,0).

For me, msise.run() for dates that are in the near future (<45 days) throws an error like:
"ValueError: cannot smooth over more time periods than exist in the data" 

This is because getApF107 would not be able to return f10.7 data, even though there is a 45-day-ap-orecast.txt file. 

1. Can you see if there is a compromised data file in your data path: geomagindices/data possible called RecentIndices.txt? May be removing that file and running the code can help? 

2. The code seems to be error-proof for a non-datetime object and gives very specific ValueErrors. Is the error occurring at _parser.py or some other place?

**Comment by tomerarnon** [comment]
Rerunning the exact same code, I am unable to reproduce the error. I'm not sure what to make of this. 
As I recall though, yes, I believe the error was _parser.py.

**Comment by scivision** [comment]
The code has changed since then, it may have been something that was fixed. I will tentatively close unless it becomes an issue again. Thanks!
